semana11/biblioteca_app/app/models/libro_model.py
from database import db


class Libro(db.Model):
    __tablename__ = "libros"

    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(100), nullable=False)
    autor = db.Column(db.String(100), nullable=False)
    edicion = db.Column(db.Integer, nullable=False)
    disponibilidad = db.Column(db.Integer, nullable=False)

    def __init__(self, titulo, autor, edicion,disponibilidad):
        self.titulo = titulo
        self.autor = autor
        self.edicion = edicion
        self.disponibilidad = disponibilidad

    def save(self):
        db.session.add(self)
        db.session.commit()

    # Obtiene todos los animales de la base de datos
    @staticmethod
    def get_all():
        return Libro.query.all()

    # Obtiene un animal por su ID
    @staticmethod
    def get_by_id(id):
        return Libro.query.get(id)

    # Actualiza un animal en la base de datos
    def update(self, titulo=None, autor=None, edicion=None,disponibilidad = None):
        if titulo is not None:
            self.titulo= titulo
        if autor is not None:
            self.autor = autor
        if edicion is not None:
            self.edicion = edicion
        if disponibilidad is not None:
            self.disponibilidad = disponibilidad
        db.session.commit()

    # Elimina un animal de la base de datos
    def delete(self):
        db.session.delete(self)
        db.session.commit()

semana11/biblioteca_app/app/models/user_model.py
import json
from database import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    roles = db.Column(db.String(50), nullable=False)

    def __init__(self, username, password, roles=["user"]):
        self.username = username
        self.roles = json.dumps(roles)
        self.password_hash = generate_password_hash(password)

    def save(self):
        db.session.add(self)
        db.session.commit()
    def delete(self):
        db.session.delete(self)
        db.session.commit()
    @staticmethod
    def get_all():
        return User.query.all()
    @staticmethod
    def get_by_id(id):
        return User.query.get(id)
    # Esta funcion encuentra un usuario por su nombre de usuario
    @staticmethod
    def find_by_username(username):
        return User.query.filter_by(username=username).first()
    @staticmethod
    def get_user_by_username(username):
        return User.query.filter_by(username=username).first()
    def has_role(self,role):
        return self.roles == role

semana11/biblioteca_app/app/controllers/libro_controller.py
from flask import Blueprint, request, flash,redirect,url_for
from models.libro_model import Libro
from views import libros_view
# Crear un blueprint para el controlador de libroes
libros_bp= Blueprint("libros", __name__)


# Ruta para obtener la lista de libroes
@libros_bp.route("/libros", methods=["GET"])
def list_libros():
    libro = Libro.get_all()
    return libros_view.render_libro_list(libros=libro)


# Ruta para obtener un libro específico por su ID
@libros_bp.route("/libros/<int:id>", methods=["GET"])
def get_libro(id):
    libro = Libro.get_by_id(id)
    if libro:
        return libros_view.render_libro_detail(libro)
    flash("no se ha podido encontrar el libro")
    return redirect(url_for("libros.list_libros"))


# Ruta para crear un nuevo libro
@libros_bp.route("/libro/create", methods=["GET","POST"])
def create_libro():
    if request.method == "POST":
        titulo = request.form["titulo"]
        autor = request.form["autor"]
        edicion = request.form["edicion"]
        disponibilidad = request.form["disponibilidad"]
        # Crear un nuevo libro y guardarlo en la base de datos
        libro = Libro(titulo=titulo,autor = autor,edicion=edicion,disponibilidad=disponibilidad)
        libro.save()
        flash("Libro creador exitosamente","success")
        return redirect(url_for("libros.get_libros"))

    return libros_view.create()


# Ruta para actualizar un libro existente
@libros_bp.route("/libros/<int:id>", methods=["GET","POST"])
def update_libro(id):
    libro = Libro.get_by_id(id)
    if request.method == "POST":
        titulo = request.form["titulo"]
        autor = request.form["autor"]
        edicion = request.form["edicion"]
        disponibilidad = request.form["disponibilidad"]
        # Crear un nuevo libro y guardarlo en la base de datos
        libro.update(titulo=titulo,autor = autor,edicion=edicion,disponibilidad=disponibilidad)
        libro.save()
        flash("El libro se actualizo correctamente")
        return redirect(url_for("libros.get_libros"))
  

    return libros_view.update(libro)


# Ruta para eliminar un libro existente
@libros_bp.route("/libros/<int:id>", methods=["DELETE"])
def delete_libro(id):
    libro = Libro.get_by_id(id)

    if not libro:
        flash("No se ha encontrado el libro")
    # Eliminar el libro de la base de datos
    libro.delete()

    # Respuesta vacía con código de estado 204 (sin contenido)
    flash("Libro se borro exitosamente")
    return redirect(url_for("libros.list_libros"))

semana11/biblioteca_app/app/controllers/user_controller.py
from flask import Blueprint, request, jsonify,redirect,url_for,flash
from models.user_model import User
from flask_login import current_user,login_user,logout_user,login_required
from werkzeug.security import check_password_hash
from views import user_view
user_bp = Blueprint("user", __name__)

@user_bp.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("user.profile",id=current_user))
    return redirect(url_for("user.login"))

@user_bp.route("/user/create", methods=["GET","POST"])
def register():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        roles = request.form["role"]

        existing_user = User.find_by_username(username)
        if existing_user:
            flash("El nombre de usuario no disponible","error")
            return  redirect(url_for("user.register"))
        else:
            new_user = User(username, password, roles)
            new_user.save()
            flash("usuario creado exitosamente","success")
            return redirect(url_for("user.profile"),new_user.id)
    return user_view.registro()

@user_bp.route("/users")
@login_required
def list_users():
    users = User.get_all()
    return user_view.usuarios(users)

@user_bp.route("/user/login", methods=["GET","POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        user = User.find_by_username(username)
        if user and check_password_hash(user.password_hash, password):
            login_user(user)
            flash("Inicio de sesion exitoso","success")
            if user.has_role("admin"):
                return redirect(url_for("user.list_users"))
            else:
                return redirect(url_for("user.profile",id=user.id))
    return user_view.login()

@user_bp.route("/profile/<int:id>")
@login_required
def profile(id):
    user = User.get_by_id(id)
    return user_view.perfil(user)
@user_bp.route("/user/logout")
def logout():
    logout_user()
    return redirect(url_for("user.login"))

semana11/biblioteca_app/app/views/libros_view.py
from flask import render_template
def render_libro_list(libros):
    # Representa una lista de libroes como una lista de diccionarios
    return render_template("libro.html",libros=libros)


def render_libro_detail(libro):
    return render_template("libro.html",libro)
def create():
    return render_template("registro.html")
def update():
    return render_template("update_libro.html")

semana11/biblioteca_app/app/views/user_view.py
from flask import render_template
def perfil(user):
    return render_template("profile.html",user=user)
def login():
    return render_template("login.html")
def registro():
    return render_template("registro.html")
def actualizar():
    return render_template("actualiar.html")
def usuarios():
    return render_template("usuarios.html")

semana11/biblioteca_app/app/templates/actualizar.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Actualizar Usuario</h2>

<form method="post" action="/users/{{ user.id }}/update">
    <div class="field">
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" 
            required class="input" value="{{ user.first_name }}">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" 
            required class="input" value="{{ user.last_name }}">
        </div>
    </div>
    <div class="field">
        <label for="username">Nombre de Usuario:</label>
        <div class="control">
            <input type="text" id="username" name="username" 
            required class="input" value="{{ user.username }}">
        </div>
    </div>
    
    <div class="field">
        <label for="role">Rol:</label>
        <div class="control">
            <div>
                <input type="text" id="role" name="role" 
                required class="input" value="{{ user.role }}">
        </div>
    </div>
    <input type="submit" value="Actualizar" class="button is-primary">

{% endblock %}

semana11/biblioteca_app/app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <title>{{ title }}</title>
</head>
<body>
    <h1 class="title">MVC</h1>
    {% if current_user.is_authenticated %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                {% if current_user.has_role("admin") %}
                <a class="navbar-item" href="{{ url_for('user.list_users') }}">
                    Lista de Usuarios
                </a>
                <a class="navbar-item" href="{{ url_for('libros.create_libro') }}">
                    Crear Libro
                </a>
                {% endif %}
                <a class="navbar-item" href="{{ url_for('user.profile', id=current_user.id) }}">
                    Perfil
                </a>
                <a class="navbar-item" href="{{ url_for('libros.list_libros') }}">
                    Lista de Libros
                </a>
                <a class="navbar-item" href="{{ url_for('user.logout') }}">
                    Cerrar Sesión
                </a>
            </div>
        </div>
    </nav>
    {% endif %}
    <div class="columns is-mobile is-centered">
        <div class="column is-half">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

semana11/biblioteca_app/app/templates/create_libro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Registrar Animal</h2>
<form method="post">
    <div class="field">
        <label for="titulo">Titulo:</label>
        <div class="control">
            <input type="text" id="name" name="titulo" required class="input" >
        </div>
    </div>
    <div class="field">
        <label for="autor">Autor:</label>
        <div class="control">
            <input type="text" id="species" name="autor" required class="input" >
        </div>
    </div>
    <div class="field">
        <label for="edicion">Edicion:</label>
        <div class="control">
            <input type="number" id="age" name="edicion" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="disponibilidad">disponibilidad:</label>
        <div class="control">
            <input type="number" id="age" name="disponibilidad" required class="input" >
        </div>
    </div>
    <input type="submit" value="Guardar Cambios" class="button is-primary">
</form>
{% endblock %}

semana11/biblioteca_app/app/templates/libro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Lista de libro</h2>
    <!-- Lista en una tarjeta donde cada libro tenga sus datos y botones para editar y eliminar, solo visibles para administradores -->
    <div class="columns is-multiline">
        {% for libro in libros %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <p><strong>Titulo: {{ libro.titulo }} </strong></p>
                            <p><strong>Autor: {{ libro.autor }}</strong></p>
                            <p><strong>Edicion: {{ libro.edicion }}</strong></p>
                            <p><strong>Edicion: {{ libro.disponibilidad }}</strong></p>
                            <div class="buttons">
                                {% if current_user.has_role('admin') %}
                                    <a href="{{ url_for('libro.update_libro', id=libro.id) }}" 
                                    class="button is-info">Editar</a>
                                    <a href="{{ url_for('libro.delete_libro', id=libro.id) }}" 
                                    class="button is-danger">Eliminar</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

semana11/biblioteca_app/app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Iniciar Sesión</h1>
    <div class="columns is-mobile is-centered">
        <div class="column is-half">
            <form method="post">
                <div class="field">
                    <label class="label">Nombre de Usuario</label>
                    <div class="control">
                        <input class="input" type="text" name="username" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Contraseña</label>
                    <div class="control">
                        <input class="input" type="password" name="password" required>
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-primary" type="submit">Iniciar Sesión</button>
                    </div>
                    <div class="control">
                        <a href="{{ url_for('user.register') }}" class="button is-info">Crear Usuario</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

semana11/biblioteca_app/app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Perfil de Usuario</h2>
<div class="card">
    <div class="card-content">
        <div class="content">
            <p><strong>Nombre de Usuario:</strong> {{ user.username }}</p>
            <p><strong>Rol:</strong> {{ user.roles }}</p>
        </div>
    </div>
</div>
{% endblock %}

semana11/biblioteca_app/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Registrar Usuario</h2>
<form method="post">
    <div class="field">
        <label for="username">Nombre de Usuario:</label>
        <div class="control">
            <input type="text" id="username" name="username" 
            required class="input">
        </div>
    </div>
    <div class="field">
        <label for="password">Contraseña:</label>
        <div class="control">
            <input type="password" id="password" name="password" 
            required class="input">
        </div>
    </div>
    <div class="field">
        <label for="role">Rol:</label>
        <div class="control">
            <input type="text" id="role" name="role" 
            required class="input">
        </div>
    </div>
    <input type="submit" value="Registrar" class="button is-primary">
</form>
{% endblock %}

semana11/biblioteca_app/app/templates/update_libro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Editar Libro</h2>
<form method="post">
    <div class="field">
        <label for="titulo">Titulo:</label>
        <div class="control">
            <input type="text" id="name" name="titulo" required class="input" value="{{ libro.titulo }}">
        </div>
    </div>
    <div class="field">
        <label for="autor">Autor:</label>
        <div class="control">
            <input type="text" id="species" name="autor" required class="input" value="{{ libro.autor }}">
        </div>
    </div>
    <div class="field">
        <label for="edicion">Edicion:</label>
        <div class="control">
            <input type="number" id="age" name="edicion" required class="input" value="{{ libro.edicion }}">
        </div>
    </div>
    <div class="field">
        <label for="disponibilidad">disponibilidad:</label>
        <div class="control">
            <input type="number" id="age" name="disponibilidad" required class="input" value="{{ libro.disponibilidad }}">
        </div>
    </div>
    <input type="submit" value="Guardar Cambios" class="button is-primary">
</form>
{% endblock %}

semana11/biblioteca_app/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Lista de Usuarios</h2>
    <!--Lista en una tarjeta donde cada usuario tenga sus datos y dos botones para editar y eliminar utilizando grid-->
    <div class="columns is-multiline">
        {% for user in users %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <p><strong>Nombre: {{ user.first_name }} </strong></p>
                            <p><strong>Apellido: {{ user.last_name }}</strong></p>
                            <div class="buttons">
                                <a href="{{ url_for('user.update_user', id=user.id) }}" 
                                class="button is-info">Editar</a>
                                <a href="{{ url_for('user.delete_user', id=user.id) }}" 
                                class="button is-danger">Eliminar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}